name: ROS 2 CI
on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.6
        with:
          path: workspace

      - name: Build and test workspace
        uses: ichiro-its/ros2-ws-action@v1.0.1
        with:
          distro: jazzy


